### ISSUE TITLE
Beware not working with latest Jinja2 3.0.1

### ISSUE THREAD

**Issue by nickerejv** [hnrkp/beware#19]
Hi,

I have been using beware for a few years now. Just love it .-)

Recently, I was forced to upgrade my environment and discovered that pip pulls an Jinja2 version that is not compatible with the current release of beware. 

When starting beware the following error is thrown:

```
$ /home/beware/beware-py-venv/bin/python /home/beware/beware-git/beware/beware.py -H the hostname -p 8181 -t "BRF Ida Tvättbokning"
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "/home/beware/beware-git/beware/beware.py", line 23, in <module>
    env = Environment(loader=PackageLoader('beware', 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/beware/beware-git/beware/beware.py", line 23, in <module>
    env = Environment(loader=PackageLoader('beware', 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 310, in __init__
    f"The {package_name!r} package was not installed in a"
ValueError: The 'beware' package was not installed in a way that PackageLoader understands.

```
Listing the Jinja2 that is being pulled by default

```
$ ./pip list | grep -i jin
Jinja2              3.0.1

```
Downgrading to Jinja2 to 2.11.3 works just fine.

Thank you and regards,
Nikolay

**Comment by hnrkp** [comment]
Hej!

I usually try to follow Ubuntu and have packages that can be fetched with apt-get and avoid pip whenever possible, but this needs to be looked at..

With the latest jinja, does it work if you replace 'beware' with __file__ on line 23 (the one that's referenced in the stack trace)?

**Comment by nickerejv** [comment]
with file, I now get this.

```
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "/home/beware/beware-git/beware/beware.py", line 24, in <module>
    env = Environment(loader=PackageLoader('file', 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'file'

```

**Comment by hnrkp** [comment]
Dang. Github interpreted stuff as markup.. Let's try again:

replace with `__file__` :)

**Comment by nickerejv** [comment]
Replaced with as per below, still the same looking error.
`env = Environment(loader=PackageLoader('__file__', 'templates'))`


```
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "beware.py", line 24, in <module>
    env = Environment(loader=PackageLoader('__file__', 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '__file__'
```

**Comment by nickerejv** [comment]
I installed service_identity as per the warning, but the same error is thrown :-(
Sorry that I am not more helpful, I have little python experience.

```
Traceback (most recent call last):
  File "/home/beware/beware-git/beware/beware.py", line 24, in <module>
    env = Environment(loader=PackageLoader('__file__', 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '__file__'

```

**Comment by hnrkp** [comment]
I will try to reproduce when I have some spare time. But try just `__file__` , not `'__file__'` and see if that helps.

**Comment by nickerejv** [comment]
done,
new error message below :-(

```
Traceback (most recent call last):
  File "beware.py", line 24, in <module>
    env = Environment(loader=PackageLoader(__file__, 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/beware/beware-git/beware/beware.py", line 24, in <module>
    env = Environment(loader=PackageLoader(__file__, 'templates'))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/home/beware/beware-py-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/home/beware/beware-git/beware/beware'
```


```
[beware@kiststart-client beware]$ ls -la
total 64
drwxr-xr-x. 5 beware beware  4096 Jul 10 16:50 .
drwxr-xr-x. 4 beware beware  4096 Jun 25 20:40 ..
-rw-r--r--. 1 beware beware 15354 Jul 10 16:49 beware.py
-rw-r--r--. 1 beware beware 15290 Jul 10 09:37 beware.py-def
-rw-r--r--. 1 beware beware  7195 Jun 25 20:40 bewatorcgi.py
-rw-r--r--. 1 beware beware     0 Jun 25 20:40 __init__.py
drwxr-xr-x. 2 beware beware  4096 Jul 10 16:49 __pycache__
-rw-r--r--. 1 beware beware   899 Jun 25 20:40 reservations.py
drwxr-xr-x. 2 beware beware  4096 Jun 25 20:40 static
drwxr-xr-x. 2 beware beware  4096 Jun 25 20:40 templates
[beware@kiststart-client beware]$ 

```

**Comment by hnrkp** [comment]
So.. We can probably work around this by replacing PackageLoader with FileSystemLoader. I'll have to fix this somehow eventually (or try to remember how to make PackageLoader work) but until then:

Replace `, PackageLoader` with `, FileSystemLoader` in the imports and replace `PackageLoader('beware', 'templates')` with `FileSystemLoader('templates')` and see how that works.

I'll gladly accept a pull request if someone gets some time before me to implement this, figure out if this is the proper pythonic way of solving the issue and sees that it's backwards compatible with jinja 2.11.

**Comment by hnrkp** [comment]
@nickerejv Did it work?

**Comment by nickerejv** [comment]
Hi 

Sorry for the delay.
As requested, the changes have been made. The app start, but it fails further on...
```
from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader('templates'))

```
```
Traceback (most recent call last):
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/protocols/basic.py", line 548, in dataReceived
    why = self.lineReceived(line)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/http.py", line 2155, in lineReceived
    self.allContentReceived()
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/http.py", line 2281, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/http.py", line 1005, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/server.py", line 229, in process
    self.render(resrc)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/server.py", line 294, in render
    body = resrc.render(self)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/twisted/web/resource.py", line 263, in render
    return m(request)
  File "/home/beware/beware-git/beware/beware.py", line 91, in render_GET
    template = env.get_template('index.html')
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/beware/beware-py-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```

regards
Nikolay

**Comment by hnrkp** [comment]
You are probably executing from somewhere else than the beware directory. Of course that should work anyway, so..

Instead of `'templates'`, let's do `env = Environment(loader=FileSystemLoader(curdir + '/templates'))`

That should do it (works on my machine..)

**Comment by nickerejv** [comment]
Thank you,
now it does work for me too :-)

regards
Nikolay
